import { colors } from "./colors";

export const colorsSemantic = {
    text: {
        primary: colors.black,
        secondary: colors.blueSari700, 
        tertiary: colors.blueSari500,
        brandBold: colors.brandPrimary700,
        primaryInverse: colors.white,
        secondaryInverse: colors.blueSari400, 
        tertiaryInverse: colors.blueSari600,
        onDarkBackground: colors.white,
        onLightBackground: colors.black,
        stateDisabled: colors.blueSari300,
      },

      background: {
        primary: colors.white,
        secondary: colors.blueSari100,  
        tertiary: colors.blueSari200,
        stateSuccessSubtle: colors.greenBellPepper100,
        stateSuccessBold: colors.greenBellPepper500,
        stateWarningSubtle: colors.goldenStone100,
        stateWarningBold: colors.goldenStone500,
        stateDangerSubtle: colors.electricCrimson100,
        stateDangerBold: colors.electricCrimson600,
        brandSubtle: colors.brandPrimary200,
        brandBold: colors.brandPrimary700,
        brandMedium: colors.brandPrimary600,
        primaryInverse: colors.black,
        stateDisabled: colors.blueSari200,
        elevation1: colors.white,
        elevation2: colors.white,
        elevation3: colors.white,
        elevationGlass1: 'rgba(255, 255, 255, 0.5)', 
        elevationGlass2: 'rgba(255, 255, 255, 0.8)',
      },

      stroke: {
        primary: colors.blueSari100,
        secondary: colors.blueSari200,
        tertiary: colors.blueSari300,
        stateSuccessSubtle: colors.greenBellPepper300,
        stateSuccessBold: colors.greenBellPepper700,
        stateWarningSubtle: colors.goldenStone300,
        stateWarningBold: colors.goldenStone700,
        stateDangerSubtle: colors.electricCrimson300,
        stateDangerBold: colors.electricCrimson700,
        brandSubtle: colors.brandPrimary300,
        brandMedium: colors.brandPrimary600,
        brandBold: colors.brandPrimary800,
        stateHover: colors.brandPrimary300,
        stateFocused: colors.brandPrimary600,
        statePressed: colors.brandPrimary800,
        stateDisabled: colors.blueSari300,
      },

      icon: {
        primary: colors.black,
        secondary: colors.blueSari600,
        tertiary: colors.blueSari400,
        stateSuccessBold: colors.greenBellPepper600,
        stateSuccessSubtle: colors.greenBellPepper200,
        stateWarningBold: colors.goldenStone600,
        stateWarningSubtle: colors.goldenStone200,
        stateDangerBold: colors.electricCrimson600,
        stateDangerSubtle: colors.electricCrimson200,
        brandBold: colors.brandPrimary600,
        brandMedium: colors.brandPrimary500,
        brandSubtle: colors.brandPrimary200,
        primaryInverse: colors.white,
        secondaryInverse: colors.blueSari300,
        tertiaryInverse: colors.blueSari500,
        onLightBackground: colors.black,
        onDarkBackground: colors.white,
        stateDisabled: colors.blueSari300,
      },

      components: {
        button: {
          primary: {
            backgroundDefault: colors.brandPrimary600,
            backgroundHover: colors.brandPrimary500,
            backgroundPressed: colors.brandPrimary800,
            backgroundFocus: colors.brandPrimary500,
            backgroundDisabled: colors.blueSari200,
            textDefault: colors.white,
            textDisabled: colors.blueSari300,
            iconDefault: colors.white, 
            iconDisabled: colors.blueSari300,
            strokeFocus: colors.brandPrimary300,
          },
          secondary: {
            backgroundDefault: colors.blueSari100,
            backgroundHover: colors.blueSari200,
            backgroundPressed: colors.blueSari300,
            backgroundFocus: colors.brandPrimary100,
            backgroundDisabled: colors.blueSari200,
            textDefault: colors.black,
            textDisabled: colors.blueSari300,
            iconDefault: colors.blueSari800,
            iconDisabled: colors.blueSari300,
            strokeFocus: colors.brandPrimary300,
          },
          // ... (outros tipos de botões: danger, outline, etc.)
        },
        toggles: {
          backgroundSelected: colors.brandPrimary600,
          backgroundHover: colors.brandPrimary500,
          backgroundFocus: colors.brandPrimary500,
          backgroundDisabled: colors.blueSari200,
          iconDefault: colors.white,
          iconDisabled: colors.blueSari300,
          strokeFocus: colors.brandPrimary300,
          backgroundUnselected: colors.blueSari200,
          strokeDefault: colors.blueSari300,
        },
        rating: {
          star: colors.goldenStone300,
          heart: colors.electricCrimson500,
          empty: colors.blueSari400,
          disabled: colors.blueSari300,
          filled: colors.goldenStone300,
        },
        input: {
          backgroundDefault: colors.white,
          backgroundHover: colors.white,
          backgroundPressed: colors.white,
          backgroundFocus: colors.white,
          backgroundDisabled: colors.blueSari200,
          textDefault: colors.black,
          textDisabled: colors.blueSari300,
          iconDefault: colors.blueSari600,
          iconDisabled: colors.blueSari300,
          strokeFocus: colors.brandPrimary600,
          strokeDefault: colors.blueSari200,
          strokeDisabled: colors.blueSari300,
          strokePressed: colors.blueSari300,
          textPlaceholder: colors.blueSari400,
          textSecondary: colors.blueSari600,
        },
        // ... (outros componentes)
      },
};